### DISCUSSION TITLE
Add support for Votronic BLE Connector (serving Battery computer and solar controller)

### DISCUSSION THREAD

**Discussion by starfish1107** [syssi/esphome-votronic#1] [Ideas]
I already have this setup [https://cumulumbus.de/smart-camper-auslesen-der-batterie-und-solarinformationen-aus-dem-votronic-bluetooth-connector/](https://cumulumbus.de/smart-camper-auslesen-der-batterie-und-solarinformationen-aus-dem-votronic-bluetooth-connector/) running on a ESP32. After success with esphome-jk-bms on another ESP32  I think it would be reasonable to have both devices on a single ESP and reporting to MQTT. The protocol seems to be sufficiently documented (see the above website). Do you think it would be possible to implement this device in esphome-jk-bms?

**Comment by syssi** [comment]
We could start a new project. The votronic device has nothing in common with the JK-BMS project. It looks like the votronic BLE connection requires BLE encryption. If I remember correctly this isn't supported by the ESPHome BLE Client component yet. I will have a look tomorrow.

**Reply by syssi** [reply]
It looks like we should give it a try using this PR: https://github.com/esphome/esphome/pull/4258

**Reply by starfish1107** [reply]
thanks for your fast reply and interest. didnt realize that its that much different. let'see but please tell me if I can help.

**Reply by syssi** [reply]
Is your setup up and running? Do you know the pin of your BLE connector and could you do some tests?

**Reply by starfish1107** [reply]
yes it is set up and running in the productive system. I know the pin which I used only when bonding with the handy app. To connect the ESP32 I only had to push the button on the BLE-Adapter (dont know why this was sufficient). I could do tests with another ESP32dev module.

**Reply by syssi** [reply]
I've pushed a first draft. Please change the MAC address and flash the example to your ESP32: https://github.com/syssi/esphome-votronic/blob/main/esp32-ble-example.yaml

Please provide the ESPHome log. I would like to know the implementation is able to connect to the BLE connector and receive some measurements/notifications (log messages prefixed with: `Notification received (handle %d): ...`).

**Reply by starfish1107** [reply]
will do tests today. actually looking for a way to dump log to a txt-file. when moving the module close to the votronic, its no longer connected to usb and mqtt.fx dumping function is reportedly broken.

**Reply by syssi** [reply]
You could pipe the output to a file:

```
esphome logs esp32-ble-example.yaml | tee -a esphome.log
```

**Reply by syssi** [reply]
Summary: The first draft is up and running. It's important to pair/bond the Votronic device with the ESPHome node. The votronic device provides these services & characteristics:

```
[60:A4:23:91:8F:55] ESP_GATTC_SEARCH_CMPL_EVT
[60:A4:23:91:8F:55] Service UUID: 0x1801
[60:A4:23:91:8F:55]  start_handle: 0x1  end_handle: 0x4
[60:A4:23:91:8F:55] Service UUID: 0x1800
[60:A4:23:91:8F:55]  start_handle: 0x5  end_handle: 0x9
[60:A4:23:91:8F:55] Service UUID: 0x180A
[60:A4:23:91:8F:55]  start_handle: 0xa  end_handle: 0x10
[60:A4:23:91:8F:55] Service UUID: 1D14D6EE-FD63-4FA1-BFA4-8F47B42119F0
[60:A4:23:91:8F:55]  start_handle: 0x11  end_handle: 0x13
[60:A4:23:91:8F:55] Service UUID: D0CB6AA7-8548-46D0-99F8-2D02611E5270
[60:A4:23:91:8F:55]  start_handle: 0x14  end_handle: 0x21
[60:A4:23:91:8F:55] Service UUID: AE64A924-1184-4554-8BBC-295DB9F2324A
[60:A4:23:91:8F:55]  start_handle: 0x22  end_handle: 0xffff
[60:A4:23:91:8F:55]  characteristic 9A082A4E-5BCC-4B1D-9958-A97CFCCFA5EC, handle 0x16, properties 0x12
[60:A4:23:91:8F:55]  characteristic 971CCEC2-521D-42FD-B570-CF46FE5CEB65, handle 0x19, properties 0x12
[60:A4:23:91:8F:55]  characteristic 9E298E7F-2594-49DE-BE51-39153A6250E4, handle 0x1c, properties 0xa
[60:A4:23:91:8F:55]  characteristic CFA6E099-FA0F-43AA-88D2-4508B986A67F, handle 0x1e, properties 0xa
[60:A4:23:91:8F:55]  characteristic D2296045-A715-4458-850F-0800C7E11CEC, handle 0x20, properties 0x1a
[60:A4:23:91:8F:55] gattc_event_handler: event=18 gattc_if=3
[60:A4:23:91:8F:55] cfg_mtu status 0, mtu 247
```

IMO the order of the `esp32_ble_tracker` output is a bit misleading. The 5 characteristics are childs of the `D0CB6AA7-8548-46D0-99F8-2D02611E5270` service (-> `start_handle: 0x14, end_handle: 0x21`).

The implementation subscribes two notification streams (`photovoltaic` and `battery`). The `throttle` option can be used to reduce the update interval of the sensor states. There are no controls or retrieval of log data implemented yet.

**Reply by starfish1107** [reply]
we had some sun today. here the info I got comparing with the pv controller lcd console:
0,3 A are shown in votronic_pv_current  as 0,03A (too low)
2 W  are shown in votronic_pv_power  as 26W    (too high)
controller_status_bitmask  should be named pv_controller_status_bitmask ... 0 means pv_controller off   9 means active  and  57 means reduce pv_charging (when batt. is already full) 
I will continue to collect more info - at the moment we still have no charging because the temperatures are too low

**Reply by syssi** [reply]
1. I've fixed the resolution of the PV current sensor
2. I've fixed the resolution of the PV power sensor
3. I've renamed the controller status bitmask and provide a interpretation as text sensor now.

If it's sunny the next time please verify the correctness of the PV controller status text sensor:

```
[21:18:04][D][text_sensor:067]: 'votronic pv controller status': Sending state 'Active'
```

**Reply by starfish1107** [reply]
'votronic pv controller status': Sending state 'Active' shows up correctly. But there are 2 more meanings known - 57 for reduce (25 according to cumulumbus - maybe under other conditions) and 0  for standby  (or off) - its a good idea to show the numbers instead of "unknown" so the meanings can be assigned (hopefully).
votronic.sensor.votronic_pv_controller_status_bitmask ,   votronic.sensor.votronic_controller_status_bitmask reflect the same value and could therefore be removed if I am not wrong.
PV current sensor and PV power sensor are correct now.
something else I verified with LCD console: battery frame byte 12  0xFF  no charge / 0x00 = charging (as with solar status there might be some other states in this byte) .  To my opinion we have all the really interesting parameters, the others will be found step by step.

**Reply by syssi** [reply]
Cool! I totally forgot that you have a display. So far I have orientated myself on the functions / displayed values of the android app. In this regard we are pretty feature complete. 

Could you create an issue per new/missing feature here: https://github.com/syssi/esphome-votronic/issues

Issues are easier to track.

**Reply by syssi** [reply]
I've introduced two new binary sensors (`charging`, `discharging`). The charging current is a 24bit floating point number now. Byte 12 of the frame is just the first part of the float which is important if we work with large numbers/currents. 

I've trouble with the decoding of the operation status. I would be happy if could provide some more readings (raw values and real mode displayed by the android app and/or LCD display).

**Reply by starfish1107** [reply]
yes, I have seen a post on cumulumbus blog about Byte 12 being part of a 24bit float.
what shall I send you? a debug or more detailed log along with corresponding screenshots of app and lcd?
Actually its not easy to attain these working conditions. I heated up the camper to get rid of the undertemperature blocking and the PV is not giving enough power, so I am using 230V charger. 
about log  just saw that you added raw value if meaning is unknown, that makes it easier.

**Reply by syssi** [reply]
I'm pretty sure the sun will come back in a few days, weeks or month. Take your time! ESPHome logs with corresponding screenshots of the app and/or the LCD display would be awesome.

**Reply by starfish1107** [reply]
maybe of interest: https://www.youtube.com/watch?v=tXYK4e92x7Q   after min 8:14  there is a list provided by votronic  -in part and for rs485 only  but the guy achieved to get infos from votronic.

**Reply by syssi** [reply]
Good catch! I've found the nodered flow at github here: https://github.com/SirReal-surreal/SirReal-surreal/blob/main/2021_08_16_Votronic.json

May be we can recycle this part:

```
//Batteriestatus
if (msg.payload[13] & (1 << 0)){
        i_phase = true
}
if (msg.payload[13] & (1 << 1)){
        u1_phase = true
}
if (msg.payload[13] & (1 << 2)){
        u2_phase = true
}
if (msg.payload[13] & (1 << 3)){
        u3_phase = true
}

//Reglerstatus
if (msg.payload[14] & (1 << 3)){
        standby = true
}
if (msg.payload[14] & (1 << 4)){
        abregelung = true
}
if (msg.payload[14] & (1 << 5)){
        AES = true
}
```

**Reply by syssi** [reply]
I tried to contact Votronic. Wish me luck! ;-)

**Reply by syssi** [reply]
basti@***

**Comment by starfish1107** [comment]
this is how it looks in iobroker - simply fantastic
![grafik](https://user-images.githubusercontent.com/9716599/214000876-08803c9f-854f-458e-a4cb-5182b97ff686.png)

and this is how it looks on my mobilephone using a simple mqtt-iot app
this is particularly interesting because it also works without a public IP when using mobile internet (using a mqtt broker however).

![photo_2023-02-04_14-09-04](https://user-images.githubusercontent.com/9716599/216769525-e5e75e3f-181a-4094-a041-b61a0c4e373a.jpg)

![photo_2023-02-04_14-21-57](https://user-images.githubusercontent.com/9716599/216770121-86d1948c-0494-41a4-be4c-8aadb6c205d0.jpg)

![photo_2023-02-04_13-05-31](https://user-images.githubusercontent.com/9716599/216770145-cfb78488-d824-487c-9385-cf929b812846.jpg)

**Reply by starfish1107** [reply]
> If you want to use the JK-BMS and Votronic component on the same ESP32 just merge the YAML files and make sure you are setting up multiple ble_client instances:
> 
> ble_client:
>   - mac_address: ${votronic_mac_address}
>     id: client0
>     pin_code: 173928
>   - mac_address: ${jkbms_mac_address}
>     id: client1



how to merge the 2 files?  remove everything which is double ?   rename  the mac_addresses in  substitutions?  how about  the 2 external_components_source: github://syssi/esphome-votronic@main and github://syssi/esphome-jk-bms@main  ?

**Reply by syssi** [reply]
Yes! If you provide your current JK-BMS configuration YAML I could merge the votronic component exemplary.

**Reply by starfish1107** [reply]
thanks - well its basically the default JK-BMS esp32-ble-example.yaml without any changes except the mac. , the board type and mqtt enabled /api disabled.  I tried it myself but too many compile errors ;-)

btw. concerning the missing votronic definitions I cant do much actually - as long as the outside temperatures are that low, charging is disabled by the bms but I´ll provide them asap.

**Reply by syssi** [reply]
Please try the attached example. It builds fine here.

[esp32-ble-example.yaml.txt](https://github.com/syssi/esphome-votronic/files/10491538/esp32-ble-example.yaml.txt)

**Reply by syssi** [reply]
What do you mean by "the topics are mixed up"? All votronic topics should be prefixed with "votronic_" and vice versa. I will analyze the log later the day. Could you explain in words what's not working?

**Reply by syssi** [reply]
I tried to group the sensors at the YAML intentional: 

Before:

```
# Votronic YAML

substitutions:
  # This is the name of the node
  # votronic/sensor/votronic_battery_capacity/state
  # ^^^^^^^^
  name: votronic

esphome:
  name: ${name}
  #     ^^^^^^^ Name of the ESPHome node
  comment: ${device_description}
  project:
    name: "syssi.esphome-votronic"
    version: 1.0.0

sensor:
  - platform: votronic_ble
    votronic_ble_id: votronic0
    # The node name is used again here
    # votronic/sensor/votronic_battery_capacity/state
    #                 ^^^^^^^^
    battery_voltage:
      name: "${name} battery voltage"
      #      ^^^^^^^
    secondary_battery_voltage:
      name: "${name} secondary battery voltage"
```

At the combined YAML:

```
substitutions:
  name: ble-gateway
  bms_name: jkbms
  votronic_name: votronic

sensor:
  - platform: votronic_ble
    votronic_ble_id: votronic0
    battery_voltage:
      name: "${votronic_name} battery voltage"
    secondary_battery_voltage:
      name: "${votronic_name} secondary battery voltage"

  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    min_cell_voltage:
      name: "${bms_name} min cell voltage"
    max_cell_voltage:
      name: "${bms_name} max cell voltage"
```

Feel free to adjust these variables/substitutions:

```
substitutions:
  name: ble-gateway
  bms_name: jkbms
  votronic_name: votronic
```

A ESPHome node name must be unique. The first part of the topic must/will change now.

```
jk-bms/sensor/jk-bms_cell_resistance_1/state
votronic/sensor/votronic_battery_capacity/state
^^^^^^^^
```

**Reply by syssi** [reply]
If you merge both YAMLs without prefixing the topics / sensor entities there will be a name clash here:

```
sensor:
  - platform: votronic_ble
    votronic_ble_id: votronic0
    current:
      name: "${name} current" # <-- nodename/sensor/nodename_current/state

  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    current:
      name: "${name} current" # <-- nodename/sensor/nodename_current/state
```

You have to make sure both current sensors gets an unique entity name.
