### ISSUE TITLE
votronic_current wrong with higher negative values 

### ISSUE THREAD

**Issue by starfish1107** [syssi/esphome-votronic#13]
- -1.3  on LCD   shows -1.25 A  on esphome-votronic
- -57A             shows  -7.9 A           

+ +30A              shows  +30A   (charging)

**Comment by syssi** [comment]
Could you provide corresponding raw values?

**Comment by syssi** [comment]
I pushed a fix to a feature branch. Could you use this feature branch temporary by updating your configuration YAML?

```
substitutions:
  name: votronic
  device_description: "Monitor a votronic device via BLE"
  external_components_source: github://syssi/esphome-votronic@fix-current-sensor
```

Reflash your device & try again. Thanks in advance!
