### ISSUE TITLE
Invalid Header 0xFF

### ISSUE THREAD

**Issue by bavariancarp** [syssi/esphome-votronic#48]
Hi,

I tried actually for 3 days to get your code running. Actually in MQTT is coming the message: invalid header 0xFF.

Its also not working, when I remove the MQTT as its recommended.

Here is my yaml:

```
substitutions:
  name: votronic-solar-charger
  device_description: "Monitor a Votronic Solar Charger via the display link port (UART)"
  external_components_source: github://syssi/esphome-votronic@main
  tx_pin: GPIO4
  rx_pin: GPIO5
  rx_timeout: 150ms

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-votronic"
    version: 3.0.0

esp8266:
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  manual_ip: 
    static_ip: 192.168.8.108
    gateway: 192.168.8.100
    subnet: 0.0.0.0
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
logger:

# If you use Home Assistant please remove this `mqtt` section and uncomment the native `api` component!
# api:

mqtt:
  broker: 192.168.8.100
  port: 1883
  username: mqtt-benutzer
  password:
  client_id: smartshunt

uart:
  - id: uart_modbus
    baud_rate: 1000
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}

votronic:
  - id: votronic0
    uart_id: uart_modbus
    rx_timeout: ${rx_timeout}
    throttle: 2s

binary_sensor:
  - platform: votronic
    votronic_id: votronic0
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"

sensor:
  - platform: votronic
    votronic_id: votronic0
    battery_voltage:
      name: "${name} battery voltage"
    secondary_battery_voltage:
      name: "${name} secondary battery voltage"
    battery_capacity_remaining:
      name: "${name} battery capacity remaining"
    current:
      name: "${name} current"
    power:
      name: "${name} power"
    battery_nominal_capacity:
      name: "${name} battery nominal capacity"
    state_of_charge:
      name: "${name} state of charge"
    charging_mode_setting_id:
      name: "${name} charging mode setting id"
    battery_status_bitmask:
      name: "${name} battery status bitmask"

text_sensor:
  - platform: votronic
    votronic_id: votronic0
    charging_mode_setting:
      name: "${name} charging mode setting"
    battery_status:
      name: "${name} battery status"
```

I hope someone can help me, to get it running.

Kind regards,

Mario
